const DASHBOARD_PATH = "/dashboard"
const SIGNUP_PATH = "/signup"
const SIGNIN_PATH = "/login"

export const SIGNUP_CALLBACK_URL = DASHBOARD_PATH
export const SIGNUP_ERROR_CALLBACK_URL = SIGNUP_PATH
export const SIGNIN_CALLBACK_URL = DASHBOARD_PATH
export const SIGNIN_ERROR_CALLBACK_URL = SIGNIN_PATH