services:
  mongodb-test:
    image: prismagraphql/mongo-single-replica:5.0.3
    container_name: mongodb
    # command: ["/bin/sh", "/docker-entrypoint-initdb.d/mongodb-init.sh"]
    environment:
      - MONGO_INITDB_ROOT_USERNAME=brandkitpilot-test-mongo-user-appdataagent
      - MONGO_INITDB_ROOT_PASSWORD=t3st
    ports:
      - "27017:27017"
    profiles:
      - test
  mongodb-dev:
    image: prismagraphql/mongo-single-replica:5.0.3
    container_name: mongodb
    # command: ["/bin/sh", "/docker-entrypoint-initdb.d/mongodb-init.sh"]
    environment:
      - MONGO_INITDB_ROOT_USERNAME=brandkitpilot-dev-mongo-user-appdataagent
      - MONGO_INITDB_ROOT_PASSWORD=d3vP&ss
    volumes:
    #  - ./mongodb-init.sh:/docker-entrypoint-initdb.d/mongodb-init.sh:ro
    #  - ../generated/mongodb-test-keyfile:/data/keyfile
      - mongodb-dev-data:/data/db
      - ./docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh:ro
    ports:
      - "27017:27017"
    profiles:
      - development
  mailpit-test:
    image: axllent/mailpit
    container_name: mailpit-test
    ports:
      - "1025:1025"
      - "8025:8025"
    profiles:
      - test

  mailpit-dev:
    image: axllent/mailpit
    container_name: mailpit-dev
    volumes:
      - mailpit-data:/data
    ports:
      - "1025:1025"
      - "8025:8025"
    profiles:
      - development

  memory-cache:
    image: valkey/valkey:latest
    container_name: memory-cache
    restart: unless-stopped
    ports:
      - "6379:6379"
  worker:
    build:
      context: ../
      dockerfile: docker/Dockerfile.worker
    container_name: worker
    restart: unless-stopped
    depends_on:
      - memory-cache
    env_file: ${ENV_FILE}
    environment:
      - REDIS_URL=redis://memory-cache:6379
      - NODE_ENV=${NODE_ENV}
      - DATABASE_HOST=mongodb
    volumes:
      - ../:/app:cached
      - /app/node_modules
      - /app/generated/prisma # must be excluded so Prisma uses the correct binaries for inside the container

  stripe-cli:
    image: stripe/stripe-cli:latest
    container_name: stripe-cli
    command: ["listen", "--forward-to", "${FORWARD_TO}"]
    environment:
      - STRIPE_API_KEY=${STRIPE_API_KEY}
    network_mode: host
    restart: unless-stopped

volumes:
  mongodb-dev-data:
  mailpit-data: