services:
  mongodb-test:
    image: mongo:7
    container_name: mongodb-test
    command: ["/bin/sh", "/docker-entrypoint-initdb.d/mongodb-init.sh"]
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=test
    volumes:
      - ./mongodb-init.sh:/docker-entrypoint-initdb.d/mongodb-init.sh:ro
      - ../generated/mongodb-test-keyfile:/data/keyfile
    ports:
      - "27017:27017"
    networks:
      - app-network
    profiles:
      - test
    healthcheck:
      test: mongosh --username admin --password test --authenticationDatabase admin --quiet --eval "db.adminCommand('ping')"
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 30s

  memory-cache:
    image: valkey/valkey:latest
    container_name: memory-cache
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - app-network
  worker:
    build:
      context: ../
      dockerfile: docker/Dockerfile.worker
    container_name: worker
    restart: unless-stopped
    networks:
      - app-network
    depends_on:
      - memory-cache
    env_file: ${ENV_FILE}
    environment:
      - REDIS_URL=redis://memory-cache:6379
    volumes:
      - ../:/app:cached
      - /app/node_modules
      - /app/generated/prisma # must be excluded so Prisma uses the correct binaries for inside the container

  stripe-cli:
    image: stripe/stripe-cli:latest
    container_name: stripe-cli
    command: ["listen", "--forward-to", "${FORWARD_TO}"]
    environment:
      - STRIPE_API_KEY=${STRIPE_API_KEY}
    network_mode: host
    restart: unless-stopped

networks:
  app-network:
    driver: bridge