FROM node:24.11.0-alpine

FROM mcr.microsoft.com/playwright:v1.56.1-noble

WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install
RUN npm install -g @better-auth/cli@1.3.34

COPY . .